# Generated by Django 5.2.9 on 2025-12-16 06:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_token_expires_at_token_used_at_alter_token_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=core.models.default_expires_at),
        ),
        migrations.AlterField(
            model_name='token',
            name='number',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
