# Generated by Django 5.2.9 on 2025-12-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_token_sequence_token_service_date_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['counter', 'service_date', 'status', 'created_at'], name='core_token_counter_5c6901_idx'),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('counter', 'service_date', 'sequence'), name='uniq_token_counter_day_sequence'),
        ),
    ]
