# Generated by Django 5.2.9 on 2025-12-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_token_core_token_counter_5c6901_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='token',
            name='uniq_token_counter_day_sequence',
        ),
        migrations.RemoveIndex(
            model_name='token',
            name='core_token_counter_5c6901_idx',
        ),
        migrations.AlterField(
            model_name='token',
            name='number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('counter', 'service_date', 'sequence'), name='uniq_counter_day_sequence'),
        ),
    ]
