# Generated by Django 5.2.9 on 2025-12-18 05:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_token_uniq_token_counter_day_sequence_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='token',
            name='uniq_counter_day_sequence',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='counter',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='token',
            name='counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.counter'),
        ),
        migrations.AlterField(
            model_name='token',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='token',
            name='sequence',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='service_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('service_date', 'number'), name='uniq_token_number_per_day'),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('service_date', 'sequence'), name='uniq_token_seq_per_day'),
        ),
    ]
