# Generated by Django 5.2.9 on 2026-01-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reservationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='customer_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='token',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='token',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['service_date', 'status'], name='core_token_service_ac6e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['service_date', 'counter', 'status'], name='core_token_service_9ec0a6_idx'),
        ),
    ]
