# Generated by Django 5.2.9 on 2026-01-02 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_token_customer_address_token_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationrequest',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='token',
            name='counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='core.counter'),
        ),
        migrations.AlterField(
            model_name='token',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
